(() => {
'use strict';
const accounts=[
 {id:'douyin',platform:'抖音',name:'城城要加油！',title:'从日常观察，到镜头前的表达。',desc:'围绕个人成长、AI 时代与交易思考持续输出口播和生活记录，把观察变成选题，用自己的语言讲给观众听。',image:'social-douyin.jpg',metrics:[['127.6 万','展示作品单条播放'],['口播 / 生活记录','主要内容形式']],samples:['AI 时代的机会与感受','消息分析与个人思考','产品进度与日常记录'],ability:'展示选题意识、真人出镜、镜头表达与字幕封面的组织能力。',note:'127.6 万为所提供截图中的单条播放量，不代表账号总播放或历史最高。'},
 {id:'channels',platform:'视频号',name:'城城要加油',title:'让校园和创业，成为有内容的日常。',desc:'围绕校园体验、咖啡店经营与同城生活创作内容，把具体场景、人物和问题组织成视频话题。',image:'social-channels-life.jpg',metrics:[['6 万','展示作品观看数'],['2.2 万','咖啡厅主题作品观看数']],samples:['在广外艺上学，300 块钱够生活一个月吗','一边上学一边运营咖啡厅的体验','揭阳过年与同城生活'],ability:'展示场景化选题、本地生活表达，以及把实体店实践转化为内容的能力。',note:'数值依据截图中的观看图标读取；仅记录展示作品，不推算到店量或营业收入。'},
 {id:'aigc',platform:'视频号',name:'陈程 AIGC',title:'把一个设定，做成系列化的人生故事。',desc:'以“人生副本”为系列主题，围绕职业、选择和时代变化制作 AIGC 叙事内容。统一的标题结构与封面，让系列更容易被辨认。',image:'social-aigc.jpg',metrics:[['4,106','展示置顶作品点赞'],['3,884 / 3,893','另外两条置顶作品点赞']],samples:['天才交易员的一生','当数字游民的一生','AI 时代的职业与人生选择'],ability:'展示系列策划、叙事设定、AI 内容加工和封面视觉的一致性。',note:'这些数值是点赞，不是播放量；故事设定是内容创作，不是个人真实职业或财务经历。'},
 {id:'zhihu',platform:'知乎',name:'Li King',title:'用文字整理思考，也与读者建立连接。',desc:'围绕学习方法、日常心得与市场观察开展文字创作，在回答和文章中组织观点、解释问题。',image:'social-zhihu.jpg',metrics:[['1.6 万','主页显示被关注'],['1.3 万','主页显示获赞']],samples:['截图显示 53 个回答、27 篇文章','学习思考与费曼学习法','个人观察与阶段性创作记录'],ability:'展示长文表达、观点组织，以及持续积累内容与读者连接的实践。',note:'粉丝口径采用截图主页的 1.6 万；“两万粉感言”为文章标题，不用于替代主页数据。'},
 {id:'campus',platform:'抖音',name:'Chen要加油',title:'从一个校园问题，找到观众愿意看的话题。',desc:'把上学、生活成本和咖啡店创业放到真实日常中表达，尝试用具体的问题作为内容切入点。',image:'social-campus.jpg',metrics:[['5.2 万','展示作品单条播放'],['校园 / 创业','内容方向']],samples:['300 块钱够生活一个月吗','上大学真的是浪费时间吗','边上学边运营一家咖啡厅'],ability:'展示校园用户视角、问题式选题，以及生活记录和创业主题的结合。',note:'5.2 万为截图中一条校园生活作品的播放；与其他账号的数值分别展示，不相加。'}
];
const campusImages=[
 {id:'sharing-room',src:'campus-sharing-room.jpg',title:'真人图书馆 · AI 分享现场',caption:'向同学讲解 AI 工具并进行现场交流。照片展示同一次分享活动的现场。',rotation:0},
 {id:'sharing-close',src:'campus-sharing-close.jpg',title:'分享中的讲解与交流',caption:'以具体工具和使用场景展开交流，在面对面沟通中练习表达。',rotation:0},
 {id:'ai-award',src:'campus-ai-award.jpg',title:'AI 工具使用分享师',caption:'2025 年“智启未来：AI 工具探索之旅”真人图书馆系列活动；广东省外语艺术职业学院图书馆，2025 年 10 月 27 日。',rotation:0},
 {id:'video-award',src:'campus-video-award.jpg',title:'宣传短视频创作 · 团队一等奖',caption:'2024 年从化区南海食街宣传短视频创作大赛团队一等奖，属于团队共同成果。',rotation:0},
 {id:'tour-award',src:'campus-tour-award.jpg',title:'导游服务 · 校内选拔赛优秀奖',caption:'2024 年度广东省职业院校学生技能大赛“导游服务”项目（高职组），广东省外语艺术职业学院选拔赛；2024 年 12 月。',rotation:-90},
 {id:'union',src:'campus-student-union.jpg',title:'学生会权益部 · 成员',caption:'外语外贸学院团委学生会权益部成员证件。助班经历按本人补充另行说明。',rotation:0}
];
const $=s=>document.querySelector(s);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const socialHTML=`<section id="social" class="section social"><div class="section-top"><div><span class="eyebrow">02 / CONTENT & COMMUNITY</span><h2>把想法讲出来，<br class="mobile-only">也把内容做出来。</h2></div><p>从真人口播，到 AIGC 故事和文字创作。<br>这些账号，记录了我的内容实践。</p></div><div class="social-proof"><div><b>127.6<span>万</span></b><p>展示作品 · 单条播放</p></div><div><b>1.6<span>万</span></b><p>知乎主页 · 被关注</p></div><div><b>4,106</b><p>AIGC 置顶作品 · 点赞</p></div><p class="proof-note">来自本人提供的账号截图<br>不同平台、不同指标分别呈现<br>不作为实时统计或总量</p></div><div class="account-tabs" role="tablist" aria-label="自媒体账号">${accounts.map((a,i)=>`<button id="account-tab-${a.id}" role="tab" aria-controls="account-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-account="${a.id}"><span>${a.platform}</span>${a.name}</button>`).join('')}</div><div id="account-panel" class="account-panel" role="tabpanel" aria-labelledby="account-tab-douyin"></div><p class="media-footnote">截图保留原始数值。点击图片可放大查看；当前提供账号与作品截图，暂未接入视频播放或账号主页直达。</p></section>`;
const campusHTML=`<section id="campus" class="section campus-section"><div class="section-top"><div><span class="eyebrow">03 / SHARE & PARTICIPATE</span><h2>把 AI 用起来，<br class="mobile-only">也把它讲明白。</h2></div><p>分享、服务与协作，都是学习的一部分。<br>这里收录部分校园活动与成果。</p></div><div class="campus-feature"><button class="campus-photo" data-evidence="sharing-room" aria-label="查看AI分享现场照片"><img src="./assets/campus-sharing-room.jpg" alt="真人图书馆活动中，分享者面对同学进行讲解" width="1707" height="1280" loading="lazy"><span>真人图书馆 · 分享现场 <b>↗</b></span></button><div class="campus-story"><span class="eyebrow">LEARN IT. EXPLAIN IT. SHARE IT.</span><h3>让同学听懂，<br>让工具变得可亲近。</h3><p>在校期间，我多次向同学和学弟学妹介绍 AI 的功能与使用方法。面对不同基础的听众，练习把自己的理解转化成更容易听懂的讲解。</p><p>参与活动、担任助班和面对面交流，也让我不断锻炼公开表达与沟通能力。</p><div class="campus-award-badge"><span>✧</span><div><b>AI 工具使用分享师</b><small>学校图书馆 · 2025.10.27</small></div><button data-evidence="ai-award" aria-label="查看AI分享荣誉证书">查看证书 ↗</button></div></div></div><div class="campus-roles"><article><span>01 / 分享</span><h3>面向同学讲解 AI</h3><p>在功能介绍和交流中，把“我会用”转化成“能讲清楚”，练习根据听众的理解调整表达。</p></article><article><span>02 / 服务</span><h3>助班与校园沟通</h3><p>曾担任助班，参与校园活动。在与同学、学弟学妹的交流中，积累沟通和组织实践。</p></article><article><span>03 / 协作</span><h3>学生会权益部成员</h3><p>参与学生会权益部工作，与班级和活动经历一起，练习服务同学与团队协作。</p></article></div><div class="honors-heading"><h3>部分活动与成果</h3><span>用照片与证书，留下实践的记录</span></div><div class="honors-grid">${campusImages.slice(1).map(p=>`<button class="honor-card" data-evidence="${p.id}"><span class="honor-thumb ${p.rotation?'sideways':''}"><img src="./assets/${p.src}" alt="${escape(p.title)}" loading="lazy"></span><span class="honor-name">${p.title}<b>↗</b></span></button>`).join('')}</div><div class="campus-reflection"><span>我的收获</span><p>从镜头前到现场分享，从独立创作到团队活动，这些经历让我更敢表达，也更重视听众是否真正理解。未来，我希望把这种能力用在 AI 工具讲解、用户沟通与内容工作中。</p></div><p class="media-footnote">另有自我管理、与人交流、创新等职业核心能力校本认证；含学号与编号的原图不作公开展示。助班经历由本人补充说明，获奖名称与级别按证书呈现。</p></section>`;
$('#approach').insertAdjacentHTML('beforebegin',socialHTML+campusHTML);
const evidence=[...accounts.map(a=>({id:'account-'+a.id,src:a.image,title:a.platform+' · '+a.name,caption:a.note,rotation:0})),...campusImages];
document.body.insertAdjacentHTML('beforeend',`<dialog id="evidence-dialog" aria-labelledby="evidence-title"><div class="dialog-heading"><div><span class="eyebrow">MATERIALS / 实践记录</span><h2 id="evidence-title"></h2></div><button class="close-dialog" id="close-evidence" aria-label="关闭图片">×</button></div><div class="evidence-stage" id="evidence-stage"><img id="evidence-image" alt=""></div><p class="evidence-caption" id="evidence-caption"></p><div class="evidence-controls"><button id="evidence-prev" aria-label="上一张图片">← 上一张</button><span id="evidence-counter"></span><button id="evidence-rotate">旋转 ↻</button><button id="evidence-next" aria-label="下一张图片">下一张 →</button></div></dialog>`);
function showAccount(id){const a=accounts.find(a=>a.id===id);if(!a)return;document.querySelectorAll('[data-account]').forEach(b=>{const active=b.dataset.account===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('#account-panel').setAttribute('aria-labelledby','account-tab-'+id);$('#account-panel').innerHTML=`<div class="account-copy"><span class="eyebrow">${a.platform} / ${escape(a.name)}</span><h3>${a.title}</h3><p>${a.desc}</p><div class="account-metrics">${a.metrics.map(([v,k])=>`<div><b>${v}</b><span>${k}</span></div>`).join('')}</div><h4>内容样本</h4><ul>${a.samples.map(s=>`<li>${s}</li>`).join('')}</ul><div class="account-ability"><b>这段实践体现了什么</b><p>${a.ability}</p></div><p class="account-data-note">${a.note}</p></div><button class="account-screenshot" data-evidence="account-${id}" aria-label="放大查看${a.name}账号截图"><img src="./assets/${a.image}" alt="${a.platform}${a.name}账号与作品原始截图" width="1206" height="2622" loading="lazy"><span>查看完整截图 <b>⤢</b></span></button>`}
$('.account-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-account]');if(b)showAccount(b.dataset.account)});
$('.account-tabs').addEventListener('keydown',e=>{const b=e.target.closest('[data-account]');if(!b)return;let i=accounts.findIndex(a=>a.id===b.dataset.account);if(e.key==='ArrowRight')i=(i+1)%accounts.length;else if(e.key==='ArrowLeft')i=(i+accounts.length-1)%accounts.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=accounts.length-1;else return;e.preventDefault();showAccount(accounts[i].id);$('#account-tab-'+accounts[i].id).focus()});
let current=0,rotation=0,trigger=null;const modal=$('#evidence-dialog');const pic=$('#evidence-image');
function fit(){if(!pic.naturalWidth)return;const w=$('#evidence-stage').clientWidth-20,h=$('#evidence-stage').clientHeight-20;const swapped=Math.abs(rotation/90)%2===1;const k=Math.min(w/(swapped?pic.naturalHeight:pic.naturalWidth),h/(swapped?pic.naturalWidth:pic.naturalHeight),1);pic.style.width=pic.naturalWidth*k+'px';pic.style.height=pic.naturalHeight*k+'px';pic.style.transform=`rotate(${rotation}deg)`}
function showEvidence(id,from){const n=evidence.findIndex(p=>p.id===id);if(n<0)return;current=n;if(from)trigger=from;const p=evidence[n];rotation=p.rotation;$('#evidence-title').textContent=p.title;$('#evidence-caption').textContent=p.caption;$('#evidence-counter').textContent=`${n+1} / ${evidence.length}`;pic.alt=p.title;pic.onload=fit;pic.src='./assets/'+p.src;if(!modal.open)modal.showModal();document.body.style.overflow='hidden';modal.scrollTop=0;requestAnimationFrame(fit)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-evidence]');if(b)showEvidence(b.dataset.evidence,b)});
$('#close-evidence').onclick=()=>modal.close();modal.addEventListener('close',()=>{document.body.style.overflow=document.querySelector('dialog[open]')?'hidden':'';if(trigger?.isConnected)trigger.focus()});
function advance(d){showEvidence(evidence[(current+d+evidence.length)%evidence.length].id)}
$('#evidence-prev').onclick=()=>advance(-1);$('#evidence-next').onclick=()=>advance(1);$('#evidence-rotate').onclick=()=>{rotation+=90;fit()};
modal.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();advance(-1)}if(e.key==='ArrowRight'){e.preventDefault();advance(1)}});
modal.addEventListener('click',e=>{if(e.target!==modal)return;const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()});window.addEventListener('resize',()=>{if(modal.open)fit()});showAccount('douyin');
})();
